### ISSUE TITLE
Output on Windows includes lots (several thousands of lines) of directory listings

### ISSUE THREAD

**Issue by jimkring** [Quansight-Labs/setup-python#3]
In my [github action run log](https://github.com/jimkring/nuitka-nogil-testing/actions/runs/11693157646/job/32564094153) I have ~7000 lines of log messages that look like below.  Note that this only appears to be happening on `windows-latest` (I also [tested on `ubuntu-latest`](https://github.com/jimkring/nuitka-nogil-testing/actions/runs/11693157646/job/32564094153) and I don't see the issue there).

![Image](https://github.com/user-attachments/assets/5e86cb03-2049-4ce9-b0cb-08e6ed19c69f)

**Comment by ngoldbaum** [comment]
I think the Python install is missing from the cache maybe?

https://github.com/jimkring/nuitka-nogil-testing/actions/runs/11693157646/job/32564094153#step:3:10

**Comment by rgommers** [comment]
> I think the Python install is missing from the cache maybe?

That looks like a reasonable guess to me. The job didn't finish, so the cache remains unpopulated. If you comment out the `Run Built App (Windows)` so the job succeeds ones, then undo the commenting-out, the next run may look better.

**Comment by jimkring** [comment]
Yes, @ngoldbaum @rgommers, after a successful run (by disabling my failing tests at the end), subsequent runs of the workflow look OK and do not show the long log messages during python installation.  Thanks!

**Comment by rgommers** [comment]
Great, thanks for confirming!
