### ISSUE TITLE
Cannot install 3.13t on Windows

### ISSUE THREAD

**Issue by ngoldbaum** [Quansight-Labs/setup-python#4]
See https://github.com/ngoldbaum/rpds/actions/runs/12039858011/job/33568648905

It looks like the python installation dies with the following error when it tries to install the second time:

```
Install Python 3.13.0 in C:\hostedtoolcache\windows\Python...
  
  Error: Error happened during Python installation
  Error: At D:\a\_temp\964a44d1-31a4-4505-93f4-cc2062ee0932\setup.ps1:131 char:5
  +     Throw "Error happened during Python installation"
  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OperationStopped: (Error happened ...on installation:String) [], RuntimeException
      + FullyQualifiedErrorId : Error happened during Python installation
  Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

**Comment by ngoldbaum** [comment]
Actually it looks like this is breaking NumPy too: https://github.com/numpy/numpy/actions/runs/12039679168/job/33567999829#step:3:30

**Comment by ngoldbaum** [comment]
Comparing with a run that succeeded, I don't see any difference between the runners: https://github.com/Quansight-Labs/setup-python/issues/4

**Comment by ngoldbaum** [comment]
Maybe this is related to the large amount of output on the successful run? Some threshold for spamming output changed?

**Comment by colesbury** [comment]
The python.org downloads is broken and the Windows installer downloads  the free threading artifacts at install time.

https://github.com/python/cpython/issues/127307

**Comment by ngoldbaum** [comment]
Fixed: https://github.com/numpy/numpy/actions/runs/12039679168/job/33572692871
